### PR TITLE
Use snapshot versions

### PR DESCRIPTION
**Pull request by feeblefakie**

### CODE REVIEW

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Comment by brfrn169** [comment]
@feeblefakie Ah sorry, I found one thing after approving this. Don't we need the snapshot repository in `build.gradle` as follows?
```gradle
    repositories {
        ...

        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
```

**Comment by feeblefakie** [comment]
@brfrn169 Thank you!
Honestly, I'm not sure how it looks up the snapshot repo. 
I thought snapshot versions are synced to the Maven central without the usual process, but it only uploads to the sonatype repos?

**Comment by feeblefakie** [comment]
@brfrn169 PTAL again. Thank you!

**Comment by brfrn169** [comment]
> I thought snapshot versions are synced to the Maven central without the usual process, but it only uploads to the sonatype repos?

@feeblefakie It seems like yes. But actually, I'm also not very sure that...

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Review by supl — APPROVED** [review]
LGTM.
Thanks!

**Pull request merged**
